# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='geodata',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
