# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestin', '0002_auto_20170304_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='social_status_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
