# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestin', '0003_activity_social_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='score',
            field=models.FloatField(default=-1),
        ),
    ]
