# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestin', '0005_auto_20170305_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='social_status_id',
            field=models.IntegerField(unique=True),
        ),
    ]
