XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXX XXXXXXXXX XXXXXX XXXXX XXX XXXXX XXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXX XXX
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
	XXXXX XXXXXXXXXXXXXXX XX
	XXXXXXXXXXXXXX XX XXXXXXXXXXXXX
XXXXXXX 
XXXXXX
	XXXXXXXX
		XXXXXXXXX XX X
			XXX XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXX XXXXXXXX

			XX
				XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
			XX
			XXXXXXXXXXXXXX X XXXXXXXXXX X
				XXX XXX X XXX XXXXXX XX XX

				XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

				XXX XX X XX X X XXXXXXXXXXXXX XXXX X

					X X XXXXXXXXXXXXXXXXXXXX
					XX XX XXXXXXX XXXX XX XXXXXXXXX XXXXXXX
					XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX

					XX XXXXXXXXXXXXXXXXXXXX XX XX X XX XXXX XXXX XX XXXXX
						XXXX X XXXXXXXXXXXXXXXXXX XXXX

						XX XXXXXXX XXXXXXXXX XX XXXXXXXXX X
							XXXXXXXXX X XXX
						X
						XXXXXXXXXXXXXXXXXXXXX
					X XXXX X
						XXXXXXXXX X XXXXX
					X
				X
				XXXXXX XXXX
			XX

			XXXX X XXXXXXXXX XXXX XXXXXXXX X X
				XXX XXX X XXXXXXXXXX
				XX XXXXXXX
					XXXXXXX
				X
				XXXXXXXXX XXXXXX XXXX XXXX XX
				XXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX XX X
					XX X XXXXXXXXXXXXXX XX X XX XXXXXXXXXX XX XXX XX XXXXXXXXXX XX XXX XX
						XXXXXXX
					X
					XXXXXXXXX XXXXXXXXXXXXXXXX XX
				XX
				XX X XXXXXXXXXXXXXX XX X XX
					XXXXXXX
				X
				XXXXXXXXXXX
			XX

			XXXXXXXX XXXX XXX 
			XXXXXXX X XXXXXXXXXXX X
				XXX XXXXXXXXXXXXX X XXXXXX
					XXXXXXXX X X
						XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXX XX
						XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
						XXXXXXXXXXX XXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
					XX
					XX X XXXXXXXXXXXXXXXX

				XXXXXX XXXX XX
					XXX X
						XXXXXXXXXXXXX X XXXXXXXXX XX XXXX
					X
					XXXXXXXX X
						XXXXXXXXX
					X
					XXXXXX
				X
				XXXXXX XXXXXXXXXXX
					XXXXXX XXXXXXXXXXXXXX
				XX
			XXXXX

			XXXXX X XXXXXXXXXXXXXXXXX
			XXX X XXXXXXXXXXXXX
			XXXXXX X XXXXXXXXXXXXX

			XX XXXX XX XXXXXXX X
				XXXXXXXXX XXXXXXXX XXXXXXXXXX X
					XXXXXXXXXXX X XXXXXXXXX
					XXXXXXXXXXXXXXXXXXXX X XXXXXXX
				XXX
			X
		XXXXX
	XXXXXXXXX
XXXXXXX
XXXXXXX